trigger:
- master

pool:
  name: Self-Hosted-Agent

variables:
- name: globalVariable
  value: "This is root level variable" 
- group: GROUP1
- group: GROUP2 

stages:
- stage:
  displayName: "Stage 1"
  variables:
    stageVariable: "This is Stage level variable"
  jobs:
  - job: BuildAndTest
    variables:
    - name: jobVariable
      value: "This is Job level variable"
    workspace:
      clean: all
    steps:
    - script: |
        echo "globalVariable :" $(globalVariable)
        echo "stageVariable :" $(stageVariable)
        echo "jobVariable :" $(jobVariable)
        echo "pipelineVariable :" $(sameNameVariable)
        echo "group1Variable :" $(GROUP1.sameNameVariable)
        echo "group2Variable :" $(GROUP2.sameNameVariable)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo ${{ variables.sameNameVariable }}
          echo "group1Variable :" $(GROUP1.sameNameVariable)
          echo "group2Variable :" $(GROUP2.sameNameVariable)