trigger:
- master


jobs:
- job: BuildAndTest
  workspace:
    clean: all
  pool:
    name: Self-Hosted-Agent

  #container: avcosystems/golang-node:1.16
  steps:
  - task: Go@0
    displayName: "Go Get"
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    displayName: "Go Build"
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Bash@3
    displayName: 'Go Test'
    inputs:
      targetType: 'inline'
      script: cgo_enabled=0 test ./...
  - task: CopyFiles@2
    displayName: "Copy files to ArtifactStaging"
    inputs:
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
       artifactName: drop

- job: OnBuildHost
  dependsOn: BuildAndTest
  pool:
    name: Self-Hosted-Agent  
  steps:
  - task: Docker@2
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Docker Build'
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageRepository)'
      command: 'build'
      Dockerfile: '$(dockerfilePath)'
      tags: '$(Build.BuildNumber)'    
  - task: ArtifactoryDocker@1
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: 'push'
      artifactoryService: '$(artifactoryServiceConnection)'
      targetRepo: '$(targetRepo)'
      imageName: '$(imageName):$(imageTag)'
