trigger: 
 - main

pool:
   name: Self-Hosted-Agent

variables:
  - group: dev

steps: 

- task: Go@0
  displayName: "Go Get"
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: "Go Build"
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: 'deployment.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     pathToPublish: '$(Build.ArtifactStagingDirectory)'
     artifactName: drop

- task: S3Upload@1
  inputs:
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    awsCredentials: 'aws_service'
    regionName: 'ap-southeast-2'
    bucketName: 'azuredevops2awss3upload'
    globExpressions: '**\*.zip'
    createBucket: true
    keyManagement: 'awsManaged'
    encryptionAlgorithm: 'AES256'
    logRequest: true
    logResponse: true
