trigger:
- master


jobs:
- job: BuildAndTest
  workspace:
    clean: all
  pool:
    vmImage: Ubuntu-latest

  container: avcosystems/golang-node:1.16
  steps:
  - task: Go@0
    displayName: 'go get'
    inputs:
      command: 'get'
      arguments: '-d'
  - task: Go@0
    displayName: 'go build'
    inputs:
      command: build  
  - task: Go@0
    displayName: 'go test'
    inputs:
      command: 'test'
      arguments: '-v'