trigger:
- master

pool:
  name: Self-Hosted-Agent

variables:
- name: sameNameVariable
  value: "This is root level variable" 

stages:
- stage:
  displayName: "Stage 1"
  variables:
    sameNameVariable: "This is Stage level variable"
  jobs:
  - job: BuildAndTest
    variables:
    - name: sameNameVariable
      value: "This is Job level variable"
    workspace:
      clean: all
    steps:
    - script: |
        echo $(sameNameVariable)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo ${{ variables.sameNameVariable }}