trigger: 
 - master

jobs:
- job: Build
  displayName: Build

  pool:
    vmImage: 'ubuntu-16.04'

  container: mcr.microsoft.com/vscode/devcontainers/go:1.16

  steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo inside container
      
        echo Hello world
        echo "$(cat /etc/os-release)"
  - task: Go@0
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'deployment.xml'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
       artifactName: drop
- job: Package
  dependsOn: Build
  condition: succeeded()

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - checkout: none
  - script: |
      aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
    displayName: 'Login to AWS'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
  - task: DownloadPipelineArtifact@1
    inputs:
      artifactName: 'MyProject'
      targetPath: '$(System.DefaultWorkingDirectory)'
  - task: Docker@2
    displayName: Build docker image
    inputs:
      repository: $(DOCKER_REPOSITORY)
      command: buildAndPush
      Dockerfile: Dockerfile
      tags: '$(Build.BuildNumber)'