trigger: 
 - master

pool:
   vmImage: 'ubuntu-latest'

container: mcr.microsoft.com/azuredocs/go:latest

steps: 

- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
