trigger:
- main

variables:
  - group: artifactory

jobs:
- job: BuildAndTest
  workspace:
    clean: all
  pool:
    name: Self-Hosted-Agent

  #container: avcosystems/golang-node:1.16
  steps:


  - task: GoTool@0
    inputs:
      version: '1.17'
  - task: Go@0
    displayName: "Go Get"
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    displayName: "Go Build"
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    displayName: "Go Test"
    inputs:
      command: 'test'
      arguments: './...'
  - task: CopyFiles@2
    displayName: "Copy files to ArtifactStaging"
    inputs:
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
       artifactName: drop

- job: OnBuildHost
  dependsOn: BuildAndTest
  pool:
    name: Self-Hosted-Agent  
  steps:

  - task: Docker@2
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Docker Build'
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageRepository)'
      command: 'build'
      Dockerfile: '$(dockerfilePath)'
      tags: '$(Build.BuildNumber)'    
  - task: ArtifactoryToolsInstaller@1
    displayName: "Install JFrog CLI"
    inputs:
      artifactoryService: 'BasicAuth-artifactory'
      cliInstallationRepo: 'https://releases.jfrog.io/ui/native/jfrog-cli/v2/'
  - task: ArtifactoryDocker@1
    displayName: "Push to Artifactory"
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: 'push'
      artifactoryService: '$(artifactoryServiceConnection)'
      targetRepo: '$(targetRepo)'
      imageName: '$(imageName):$(imageTag)'

  - task: CmdLine@2
    inputs:
     script: |
       echo Write your commands here
        docker tag subudear.jfrog.io/helloworldrepo-docker/helloworld:$(Build.BuildNumber) jfrog2azure.azurecr.io/helloworldrepo-azure/helloworld:$(Build.BuildNumber)
        echo Hello world


  - task: Docker@2
    inputs:
      containerRegistry: 'jfrog2azure'
      repository: 'jfrog2azure.azurecr.io/helloworldrepo-docker/helloworld'
      command: 'push'
      tags: '$(Build.BuildNumber)'
